kind: Service
apiVersion: v1
metadata:
  name: titsuite2-0-service
  labels:
    name: titsuite2-0
spec:
  ports:
    - nodePort: 30163 
      port: 8080      
      targetPort: 8080  
      protocol: TCP
  selector:           
    app: titsuite2-0
  type: NodePort       

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: titsuite2-0-deployment
spec:                
  selector:         
    matchLabels:
      app: titsuite2-0
  replicas: 2       
  template:
    metadata:
      labels:        
        app: titsuite2-0
    spec:
      containers:
        - name: titsuite2-0
          image: othmaneaj/titsuite2.0
          ports:
            - containerPort: 8080                
          