apiVersion: apps/v1
kind: Deployment
metadata:
  name: titsuite2-0-deployment
  labels:
    app: titsuite2-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titsuite2-0
  template:
    metadata:
      labels:
        app: titsuite2-0
    spec:
      containers:
      - name: titsuite2-0
        image: othmaneaj/titsuite2.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: titsuite2-0-service
spec:
  type: NodePort
  selector:
    app: titsuite2-0
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100